#!/bin/bash

# 🚀 DEPLOYMENT SCRIPT - Check-Simi
# Este script contiene los EXACTOS pasos para hacer deploy

echo "=========================================="
echo "🚀 CHECK-SIMI DEPLOYMENT GUIDE"
echo "=========================================="
echo ""

echo "📋 PASO 1: SUPABASE SETUP"
echo "---"
echo "1. Ir a: https://supabase.com/dashboard"
echo "2. Crear nuevo proyecto"
echo "3. Copiar en SQL Editor el contenido de 'schema.sql'"
echo "4. Ejecutar el script SQL"
echo "5. Crear usuario admin:"
echo "   - Email: drhdogu@hotmail.com"
echo "   - Password: simicheck"
echo "6. Settings → API → Copiar estas credenciales:"
echo ""
echo "   NEXT_PUBLIC_SUPABASE_URL = ?"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY = ?"
echo ""
echo ""

echo "📋 PASO 2: GITHUB SETUP"
echo "---"
echo "1. Ir a: https://github.com/new"
echo "2. Repository name: check-simi"
echo "3. Description: Control de Asistencia con QR y Geofencing"
echo "4. Make it Public"
echo "5. Create repository"
echo ""
echo "6. En terminal local, ejecutar:"
echo ""
echo "   git remote add origin https://github.com/TU_USUARIO/check-simi.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "7. Esperar a que termine el push"
echo ""
echo ""

echo "📋 PASO 3: VERCEL DEPLOY"
echo "---"
echo "1. Ir a: https://vercel.com/dashboard"
echo "2. Click 'Add New' → 'Project'"
echo "3. Importar repositorio GitHub 'check-simi'"
echo "4. Click 'Continue'"
echo ""
echo "5. ENVIRONMENT VARIABLES (importante!):"
echo "   - Variable 1:"
echo "     Name: NEXT_PUBLIC_SUPABASE_URL"
echo "     Value: (pegar URL de Supabase)"
echo ""
echo "   - Variable 2:"
echo "     Name: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "     Value: (pegar clave anónima de Supabase)"
echo ""
echo "6. Click 'Deploy'"
echo "7. Esperar 2-3 minutos"
echo ""
echo ""

echo "=========================================="
echo "✅ DEPLOYMENT COMPLETADO!"
echo "=========================================="
echo ""
echo "Tu aplicación estará en:"
echo "https://check-simi.vercel.app"
echo "(o tu custom domain)"
echo ""
echo "Credenciales Admin:"
echo "  Email: drhdogu@hotmail.com"
echo "  Password: simicheck"
echo ""
echo "=========================================="
